version: '2'
services:
  drone-delivery:
    build:
      context: .
      dockerfile: Delivery/Api/Dockerfile
    container_name: dronedelivery
    restart: unless-stopped
    ports:
      - '5002:80'
    networks:
      - net
  pagamento:
    build:
      context: .
      dockerfile: Pagamento/Api/devboost.dronedelivery.pagamento/Dockerfile
    container_name: pagamento
    restart: unless-stopped
    ports:
      - '5000:80'
    networks:
      - net    
networks:
  net:
    driver: bridge
